/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/github/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startGitHubAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/device/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveDeviceAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/device/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangeDeviceAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDevices"];
        put?: never;
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/environments/{environment}/snapshots/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLatestSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/environments/{environment}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEnvironmentStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StartGitHubAuthRequest: {
            deviceName: string;
        };
        StartGitHubAuthResponse: {
            deviceCode: string;
            userCode: string;
            verificationUrl: string;
            expiresIn: number;
        };
        ApproveDeviceAuthRequest: {
            deviceCode: string;
            /** Format: email */
            actorEmail: string;
        };
        ExchangeDeviceAuthRequest: {
            deviceCode: string;
        };
        ExchangeDeviceAuthResponse: {
            token: string;
            /** Format: email */
            actorEmail: string;
        };
        CreateWorkspaceRequest: {
            name: string;
            deviceId: string;
        };
        Workspace: {
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            members: components["schemas"]["Member"][];
        };
        Member: {
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "owner" | "maintainer" | "viewer";
        };
        RegisterDeviceRequest: {
            name: string;
            encryptionPublicKey: string;
            signingPublicKey: string;
        };
        Device: {
            id: string;
            name: string;
            encryptionPublicKey: string;
            signingPublicKey: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateSnapshotRequest: {
            workspaceId: string;
            environment: string;
            createdByDevice: string;
            manifestSignature: string;
            keyEnvelopes: components["schemas"]["KeyEnvelope"][];
            secrets: components["schemas"]["SecretItem"][];
        };
        Snapshot: {
            snapshotId: string;
            workspaceId: string;
            environment: string;
            version: number;
            createdByDevice: string;
            /** Format: date-time */
            createdAt: string;
            manifestSignature: string;
            keyEnvelopes: components["schemas"]["KeyEnvelope"][];
            secrets: components["schemas"]["SecretItem"][];
        };
        KeyEnvelope: {
            deviceId: string;
            recipient: string;
            encryptedKey: string;
        };
        SecretItem: {
            name: string;
            ciphertext: string;
            nonce: string;
            aadHash: string;
            valueChecksum: string;
        };
        EnvironmentStatus: {
            workspaceId: string;
            environment: string;
            latestVersion: number;
            localVersion: number;
            outOfDate: boolean;
        };
    };
    responses: never;
    parameters: {
        WorkspaceId: string;
        Environment: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startGitHubAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartGitHubAuthRequest"];
            };
        };
        responses: {
            /** @description Device verification session created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartGitHubAuthResponse"];
                };
            };
        };
    };
    approveDeviceAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveDeviceAuthRequest"];
            };
        };
        responses: {
            /** @description Device flow approved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exchangeDeviceAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeDeviceAuthRequest"];
            };
        };
        responses: {
            /** @description Device token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeDeviceAuthResponse"];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Workspace created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices registered to the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        devices: components["schemas"]["Device"][];
                    };
                };
            };
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceRequest"];
            };
        };
        responses: {
            /** @description Device registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
        };
    };
    createSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSnapshotRequest"];
            };
        };
        responses: {
            /** @description Snapshot stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    getLatestSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                environment: components["parameters"]["Environment"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest snapshot metadata and encrypted payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    getEnvironmentStatus: {
        parameters: {
            query?: {
                local_version?: number;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                environment: components["parameters"]["Environment"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment sync status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentStatus"];
                };
            };
        };
    };
}
